### ISSUE TITLE
Resolve Problem with Handling Json Tweet Date

### ISSUE THREAD

**Issue by marcosnasp** [marcosnasp/java-9-labs#1]
At running this command :

```console
foo@bar:~$ java -classpath lib/jackson-core-2.9.5.jar:lib/jackson-databind-2.9.5.jar:lib/jackson-annotations-2.9.0.jar:lib/org.tweetsum.jar org.tweetsum.Main < tweets.json
```
<pre>
Exception in thread "main" com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `java.sql.Timestamp` from String "Sun Apr 03 23:48:36 +0000 2011": expected format "EEE MMM dd HH:mm:ss ZZZZZ yyyy"  at [Source: (BufferedInputStream); line: 32, column: 21] (through reference chain: java.util.ArrayList[0]->org.tweetsum.Tweet["created_at"]) 	at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:67) 	at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:1548) 	at com.fasterxml.jackson.databind.DeserializationContext.handleWeirdStringValue(DeserializationContext.java:910) 	at com.fasterxml.jackson.databind.deser.std.DateDeserializers$DateBasedDeserializer._parseDate(DateDeserializers.java:189) 	at com.fasterxml.jackson.databind.deser.std.DateDeserializers$TimestampDeserializer.deserialize(DateDeserializers.java:335) 	at com.fasterxml.jackson.databind.deser.std.DateDeserializers$TimestampDeserializer.deserialize(DateDeserializers.java:320) 	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:136) 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288) 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151) 	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286) 	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245) 	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27) 	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4001) 	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3065) 	at org.tweetsum.Main.main(Main.java:15)
</pre>

**Comment by marcosnasp** [comment]
```code
@JsonFormat(shape = JsonFormat.Shape.STRING,
                pattern = "EEE MMM dd HH:mm:ss Z yyyy",
                locale = "en", // fix using Locale
                timezone = "GMT")
```
